name: '🐛 Bug Report'
description: Create a new ticket for a bug.
title: '🐛 [BUG] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: "# Thanks for taking the time to fill out this bug report"
  - type: checkboxes
    id: packages
    attributes:
      label: Which packages you want to submit?
      description: You may select more than one.
      options:
        - label: @rn-flix/auto-image
        - label: @rn-flix/snackbar
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: Please enter an explicit description of the bug.
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: 'Reproduction steps'
      description: Step to reproduce the bug
      placeholder: step by step to reproduce the bug
    validations:
      required: true