name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Jest Tests
        run: yarn test --coverageReporters="json-summary" --coverageReporters="text"

      - name: Jest Coverage Comment
        if: always() && github.event_name == 'pull_request'
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: ./coverage/coverage-summary.json
          title: "Test Coverage Report 🚀"
          badge-title: "Coverage"
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          remove-deprecated-reports: true
